version: "2"

services:
  nginx:
    build: ./containers/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - nodejs
  nodejs:
    build: ./containers/nodejs
    working_dir: "/usr/local/data"
    volumes:
      - "./data/nodejs:/usr/local/data"
      - "./tools:/usr/local/tools"
    ports:
      - 10081:10081
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    command: /usr/local/tools/wait-for-mysql.sh mysql root root 3306 node app.js
    links:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DB: wikiq
